fix: [CI] cryptography bump to 35.0.0
this PR aims to solve the following error raised during CI:

````
ERROR: spid-compliant-certificates 0.5.3 has requirement cryptography==35.0.0, but you'll have cryptography 38.0.1 which is incompatible.
````